// Posts action types
export const FETCH_POSTS_REQUEST = 'FETCH_POSTS_REQUEST';
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';
export const FETCH_POSTS_FAILURE = 'FETCH_POSTS_FAILURE';

export const FETCH_POST_REQUEST = 'FETCH_POST_REQUEST';
export const FETCH_POST_SUCCESS = 'FETCH_POST_SUCCESS';
export const FETCH_POST_FAILURE = 'FETCH_POST_FAILURE';

export const CREATE_POST_REQUEST = 'CREATE_POST_REQUEST';
export const CREATE_POST_SUCCESS = 'CREATE_POST_SUCCESS';
export const CREATE_POST_FAILURE = 'CREATE_POST_FAILURE';

// Subreddits action types
export const FETCH_SUBREDDITS_REQUEST = 'FETCH_SUBREDDITS_REQUEST';
export const FETCH_SUBREDDITS_SUCCESS = 'FETCH_SUBREDDITS_SUCCESS';
export const FETCH_SUBREDDITS_FAILURE = 'FETCH_SUBREDDITS_FAILURE';

export const CREATE_SUBREDDIT_REQUEST = 'CREATE_SUBREDDIT_REQUEST';
export const CREATE_SUBREDDIT_SUCCESS = 'CREATE_SUBREDDIT_SUCCESS';
export const CREATE_SUBREDDIT_FAILURE = 'CREATE_SUBREDDIT_FAILURE';

// UI action types
export const SET_LOADING = 'SET_LOADING';
export const SET_ERROR = 'SET_ERROR';
export const CLEAR_ERROR = 'CLEAR_ERROR';
export const SET_SELECTED_SUBREDDIT = 'SET_SELECTED_SUBREDDIT'; 